version: '3'
services:
  cluster-logstash:
    container_name: cluster-logstash
    image: docker.elastic.co/logstash/logstash:7.0.0
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - cluster-network

  cluster-filebeat:
    container_name: cluster-filebeat
    image: cluster-filebeat
    build: ./filebeat
    depends_on:
      - cluster-logstash
    volumes:
      - ./filebeat/example.log:/tmp/example.log
    networks:
      - cluster-network

networks:
  cluster-network: