version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - /c/Users/workspace/docker_examples/docker_compose_hit_counter:/code
    redis:
        image: "redis:alpine"