version: '3'

networks:
  terracotta-net:

services:
  client:
    build: sample-ehcache-client/
    #image: terracotta/sample-ehcache-client:4.3.5
    networks:
     - terracotta-net
    environment:
     - TERRACOTTA_SERVER_URL=terracotta-1:9510,terracotta-2:9510

  terracotta-1:
    hostname: terracotta-1
#    build: server/
    image: terracotta/terracotta-server-oss:4.3.5
    environment:
     - TC_SERVER1=terracotta-1
     - TC_SERVER2=terracotta-2
    networks:
     - terracotta-net
    ports:
     - "9540:9540"

  terracotta-2:
    hostname: terracotta-2
#    build: server/
    image: terracotta/terracotta-server-oss:4.3.5
    environment:
     - TC_SERVER1=terracotta-1
     - TC_SERVER2=terracotta-2
    networks:
     - terracotta-net
    ports:
     - "19540:9540"