DROP TABLE IF EXISTS gauth_creds;
DROP SEQUENCE IF EXISTS HIBERNATE_SEQUENCE;

CREATE TABLE gauth_creds (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(250) UNIQUE NOT NULL,
    secret_key VARCHAR(250) NOT NULL
);
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 3 INCREMENT BY 1;