heartbeat.config.monitors:
  path: /usr/share/heartbeat/monitors.d/*.yml
  reload.enabled: true
  reload.period: 1s
output.elasticsearch:
  hosts:
    - cluster-elasticsearch:9200
setup.kibana.host: 'http://cluster-kibana:5601'
#setup.dashboards.enabled: true